server:
  port: 8081

spring:
  application:
    name: ms-sri

sri:
  base-url: https://srienlinea.sri.gob.ec/sri-catastro-sujeto-servicio-internet/rest/ConsolidadoContribuyente
  timeout-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    ec.edu.fica: DEBUG
